travis:
  secure:
    BINSTAR_TOKEN: KLC5PrJTUBe/6NfFC0sXAaVwzSDjae0JZZLvwWROVjjq4FArZgI4BsD/xIf07wgaGIdY8QqcEDo5axDF32ENE0rrQPCq6uUUOzZep8D2gYVTHZsbkPaVvNd6BMuTvURxXLfvxQlMg3W8a7dDgnBNebXvGrmJsN64GrnOPRyYRa85H+FX2N9MDbNHS68vcDwJJXk/e1bDfAQkBrXXodqBy/7i/81wi7/vm6R6Jwc1q5SC9RN3hHO+7PED/7wazWoIEwRt3p7mV3B+KcQ8j2kj4in99Gp9tEU7ks6DnxZDMRiq4L0xQekYQ9IvUcY8Nao2u2UhJXklp9utTYq0GtEjExVIuiFH/HJaUYzi+pqd4qgVM5/x+HXhx1oTAvK3oQnLrAFhzqg3PTfxtZs074BF5mXzQdGJDahfXOXFUkgrvFQqjJqLg1F95h109rB9a/9iX1/I6j1ff3ahuMyyEbeGdNsGWopniInQR845BKdMkn6O7Ol6UciZWofx36y7i4lESx9XMvMry9qgBxyXqWmfM2VZQONB6qZgiDHhYM77tJjBff2eCBHWDFmKbF7u0URzOmRp5uFRyjis5XS6RRASPIXZTM/BtVLG8Ch3P31NEsshAonrgXoHOUyUGpVTF/WlVLZWNUWaNCb0ds/U4pWbfwQG4aWje2EGmEj3H1ezZ6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
