travis:
  secure:
    BINSTAR_TOKEN: NFKvQi38kdfjauemRENUgOhEb40Vvx/A0B64wWhayAoXn13qhXRNgmp22sFogXFjC/Xmv2+Qa0bJvMPV40HWsWKXeiEfFrXI8EGVGVAFGMVDRNvFmTKbK3rf2exgMrC6jdZ1K93kMRUT8X4dDzTMUV+6rNbg8StSBAiJ2HqmU32ML0WG+oxTYHWSsSmS7L2D2ei58hxdG1CyX6uJgjN9y0OFMVlCxTaaOqoogq2Y6mMpJMIjwfTO1YD7RaIZ70uigLzMQvVaNzmG7dm3YpcIT6mwBXPdnHLpGhS9r3fajbKfA8hVCcvPgzcB+NgRKqAT6Iw9EhG5P4G5E92WFc4ikD0u5karhHCbO4xNAYrlKQv9G0kno3VGp+PdZnoH47urqzBa2xxC1x2uj781JDoGH2/YxvxbCRtdH+/Fm6NWUlbi33sChmigkZAUYLaTBfWWZHJM7h79J464gsne/PNLT44WK2jHOQZxJmyD2aKoTPGyaGT8105Duksr4CugNRBBObAq3Cg3/I/5jxrJuQDbNdR91nmNRKSsn+SHUmBG7aQ9xwpeCTdcuO0QxnZ/3cgg+x7QxD5PEh9ZViaSVmGnHiwEEIvsAmPsxuMJkFPOFYao+LpEBm5kE72ilzTSWWB6Qp+R7hmybn47QmAIzwaarMJ8Rz/JxyiWXjQWzCtQK6M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
