travis:
  secure:
    BINSTAR_TOKEN: qmnfs2RJsMIAmSNxi4gxOfDqksO7tWRD3Em4qFPdcAXVQiAZp8WK5Za61vRCRsGviY2jCav9wYSnKXhn+CI6BKZJ/EfF/WYNW9yewVuSVyM5blgZMyhgRjLI8jrZ172203VJeQ86fzZYEOsf/hjLeC/5tljUXnbllg48WUMzQteLLxznbaWzRBsWOAKVEBabCRWkkhiIzmOfRcLAQkv8DKj61pOcNzodQT0TO1NoW+ZwX/fws1lnxt7OcXoF972VSQeGFcdNz9UZCwm21vx/ht3JEC9M4/QPTphTb7e6N9OLMomL3lGnlS4mBoRUpb++CpxfZwGFItEyb/anmWRnfUEtl8++3HpZxVdxYZUSTO6hUe6mpfPciy5p7Rz79BeKBHl2UKzUB7a8STgfUZ96f1DjctuZRhe6L57AVV+gwxqDnF1o7xjcbruN6PIwhLNnagDu7AFzN02hrRUQv/LBDfsV+9Gl1tUrQpkl0LwYoNBWDCTEMmUmyHpD/JpVB/YY1AADT51VxU8eukY/3Y/196NlnDHZn/BBd6dlzyA74kEhejhmucILOJp1yyfIM/7524qpUfPrq1hThVeB8u+hS3yCLrNKtqeeCXg4Fst+MrVxn1IAgsvymwy56we7hxcfI6FDkARbvgK8OBKfa5kmVRNu4FZlo8H+MHzYL441kSk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
