travis:
  secure:
    BINSTAR_TOKEN: HsMVwrsSAdlY65QHfZkUGSeO2/P9Gm8nOKS1oFhAyIQQLxFN/WJwE/VajD9j7bWNkT28AT1SS1EMXhW+ZTFj7+B2lv53GHXow05PTC3zZR91Z78esN4fX7eq7gJ+CFk/rZ9DfNWkHmn2qRGsMsSaYYMNZNRksJBJEkoTFpxH0Xz5JESU/0RRnpxToEdbcACKG/+vHjWeXljiCq8vxVI+56ZfShi5Vzubly+YF1uhenXfWbll5aQE6OR5vOtSagPSYDolgJ1+bQS+Z1YJX//I5F33lgYjcM9nbeMsWykOCDTJHdUBAUkDqddgb2x9Xnw/WUorADmgwuMQBd4Ko5bqSTFj/RpkUHrjsT02U0rWrCksHIH992B59IlVgS1hRI6fxm+cgFutRyxudH0pnHbEKJQqyusNy3BZNw/Y4vsFFwler8OwfZBleVt9E9qdVoYdNCmdjNR8YBWVttbQSjEphrWT1Q3J6Ftq6xjnPub3s8CecJVxaY1eakWkfktZRh/FSDcYN6st8QlmQx9iY96DIo3ivcilVbMoCBtGtmSSmsnbwltwHbwfv7a1v3hr6WIepa3aoW9GgcqN16wMeWFUJRqwyly4VcKdIpIKQuw5o/fGnlf9CzWY3tD8ZswbpTgY4sN266Xu8iRfwuuBssC6xYtgn69bBqnn9psPzMm9CRw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
